### ISSUE TITLE
As a user, I want to have to login (for security purposes) so that I can access my account's features.

### ISSUE THREAD

**Issue by denizakcal** [denizakcal/SOEN341_Project#19]
As a user, I want to have to login (for security purposes) and be able to do so (to be able to access my account's features).

The password should be verified from the server's (Postgresql) database.

**Comment by AnnieTran13** [comment]
Reference issue #7

**Comment by EwayWen** [comment]
General tasks: Set up authentication service, assign users unique tokens, tie tokens to user information

**Comment by EwayWen** [comment]
Login will not be implemented
