### ISSUE TITLE
As a user, I want to be able to reset forgotten passwords.

### ISSUE THREAD

**Issue by denizakcal** [denizakcal/SOEN341_Project#20]
As a user, I want to be able to reset forgotten passwords (via email).

@EwayWen, I know you mentioned this in https://github.com/denizakcal/SOEN341_Project/issues/7, but I feel like this should be separated into its own user story (because I think that creating, recovering or logging into an account are three different (albeit very-related) requirements).

(The following is the issue for logging in to an account.: https://github.com/denizakcal/SOEN341_Project/issues/19)

Reference issue #7.

**Comment by EwayWen** [comment]
General Tasks: Create password reset mechanism, create database method to change password

**Comment by EwayWen** [comment]
Passwords will not be implemented
